name: Build and Push Gravitino Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: meta
        run: echo "IMAGE=ghcr.io/ruffin-galactic/gravitino:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE
      - name: Save image as tarball
        run: docker save $IMAGE -o gravitino.tar
      - name: Upload tarball to release
        uses: softprops/action-gh-release@v2
        with:
          files: gravitino.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
