name: Build and Push Gravitino Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: meta
        run: echo "IMAGE=ghcr.io/ruffin-galactic/gravitino:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE .
        
      - name: Push image to GHCR
        run: docker push $IMAGE

      - name: Save image to tarball
        run: docker save $IMAGE -o gravitino.tar

      - name: Tag commit as 'latest' and push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -f latest
          git push -f origin latest
      - name: Wait for GitHub to register tag
        run: sleep 50

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Gravitino Bootstrapper
          body: |
            This release includes the latest Gravitino bootstrapper image.
            Load it locally with:
            ```
            curl -L -o gravitino.tar https://github.com/${{ github.repository }}/releases/download/latest/gravitino.tar
            docker load -i gravitino.tar
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tarball to Release
        uses: softprops/action-gh-release@v2
        with:
          files: gravitino.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
